name: Release Workflow

on:
  release: 
    types: [released]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: testnet #change to mainnet before production

    strategy:
      matrix:
        node-version: ['20.x']

    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn install

      - name: Compile
        run: yarn run compile

      - name: Run Tests
        run: yarn hardhat test test/erc3643/**/**.ts --network hardhat

      # - name: Run HTS Tests
      #   run: yarn hardhat test test/erc4626/**.ts --network testnet

      - name: Create deployment folder
        run: mkdir -p ./data/deployments

      - name: Run Deploy
        run: yarn run deploy --network testnet #change to mainnet before production
      
      - name: Export Contract Addresses
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          commit_options: '--no-verify --signoff'
          branch: main
          push_options: '--force'
          file_pattern: './data/deployments/*.json'
